stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: your-docker-image-name
  DOCKER_REGISTRY: registry.gitlab.com

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME .
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
